version: '3'
services:
  elections-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  # Nginx
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: 127.0.0.1:5000
      SERVERNAME: elections.ccss.carleton.ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt